# Generated by Django 2.2 on 2021-02-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwsBlackList',
            fields=[
                ('email', models.EmailField(max_length=500, primary_key=True, serialize=False)),
                ('bounce', models.BooleanField(default=False)),
                ('complaint', models.BooleanField(default=False)),
            ],
        ),
    ]
