# Generated by Django 3.1 on 2025-09-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsdjangoses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.JSONField(blank=True, default=dict)),
                ('delivery', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
            ],
        ),
    ]
